version: '3.7'

services:
  app:
    container_name: app
    build:
      context: app
      dockerfile: 'Dockerfile'
    ports:
      - 8080:8080
    networks: 
      - app-metrics

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus:/etc/prometheus"
    ports:
      - 9090:9090
    networks:
      - app-metrics

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - "./grafana/datasources:/etc/grafana/provisioning/datasources"
    networks:
      - app-metrics

networks:
  app-metrics:
    driver: bridge